export default {
    changerLangue: "en → fr",
    prestataires: "Providers",
    associations: "Associations",
    billetterie: "Ticketing",
    boutique: "Goodies Shop",
    acces: "Access",
    classementActivites: "Activity Ranking",
    pageAdmin: "Admin Page",
    pagePrestataire: "Provider Page",
    profil: "Profile",
    deconnexion: "Logout",
    acceder : "Access",
    dateDebut : "September 1st 2025",
    debut : "Event begins in : ",
    accederPage : "Access Page",
}