export default {
    "titre": "Ticketing",
    "sousTitre": "Book your tickets and experience the unique festival!",
    "reservationTitre": "Ticket Reservation",
    "prenom": "First Name",
    "prenomPlaceholder": "Your first name",
    "nom": "Last Name",
    "nomPlaceholder": "Your last name",
    "email": "Email",
    "emailPlaceholder": "Your email",
    "typeBillet": "Ticket Type",
    "selectType": "-- Select the ticket type --",
    "adulte": "Adult",
    "enfant": "Child",
    "senior": "Senior",
    "quantiteBillet": "Number of Tickets",
    "quantiteBilletPlaceholder": "Number of tickets",
    "supprimerBillet": "Remove this ticket type",
    "ajouterBillet": "Add a ticket type",
    "total": "Total",
    "passerPaiement": "Proceed to payment",
    "recapitulatifCommande": "Order Summary",
    "billets": "Tickets",
    "paiementTitre": "Payment",
    "numCarte": "Card Number",
    "numCartePlaceholder": "Card number",
    "dateExpiration": "Expiration Date",
    "cvv": "CVV",
    "cvvPlaceholder": "CVV",
    "totalAPayer": "Total to Pay",
    "payer": "Pay"
}