export default {
    monProfil: "My Profile",
    mesReservations: "My Reservations",
    mesNotifications: "My Notifications",
    donneesPersonnelles: "Personal Data",
    modifier: "Edit",
    sauvegarder: "Save Changes",
    madameMonsieur: "Mr./Ms.",
    telephone: "Phone Number",
    email: "Email",
    adresse: "Address",
    motDePasse: "Password",
    changerMdp: "Change Password",
    accepter: "Accept",
    motDePasseActuel: "Current Password",
    motDePassePlaceholder: "Your password",
    nouveauMotDePasse: "New Password",
    nouveauMotDePassePlaceholder: "Your new password",
    verificationMdp: "Password Verification",
    verificationMdpPlaceholder: "Confirm your password",
    reservationLe: "Reservation on",
    a: "at",
    annuler: "Cancel",
    aucuneNotifications: "No notifications",
    nomPrenomPlaceholder: "Full Name",
    telephonePlaceholder: "Phone Number",
    emailPlaceholder: "Email",
    adressePlaceholder: "Address"
}
