export default {

    title: "Vendor Form",
    nom: "Name:",
    nom_en : "Name (EN):",
    description: "Description:",
    description_en: "Description (EN):",
    descriptionAccueil: "Welcome Description:",
    descriptionAccueil_en: "Welcome Description (EN):",
    categorie: "Category:",
    idEmplacement: "Location ID:",
    image: "Image:",
    previewImageAlt: "Image Preview",
    servicesSectionTitle: "Services:",
    nomService: "Service Name:",
    descriptionService: "Service Description:",
    lienService: "Service Link:",
    statutService: "Service Status:",
    statutActif: "Active",
    statutInactif: "Inactive",
    supprimerService: "Remove Service",
    ajouterService: "Add Service",
    soumettre: "Submit",
    dons : "Donations:",
}