export default {
    "titre": "Billetterie",
    "sousTitre": "Réservez vos places et vivez l'expérience unique du festival !",
    "reservationTitre": "Réservation de Billet",
    "prenom": "Prénom",
    "prenomPlaceholder": "Votre prénom",
    "nom": "Nom",
    "nomPlaceholder": "Votre nom",
    "email": "Email",
    "emailPlaceholder": "Votre email",
    "typeBillet": "Type de billet",
    "selectType": "-- Sélectionnez le type de billet --",
    "adulte": "Adulte",
    "enfant": "Enfant",
    "senior": "Senior",
    "quantiteBillet": "Nombre de billets",
    "quantiteBilletPlaceholder": "Nombre de billets",
    "supprimerBillet": "Supprimer ce type de billet",
    "ajouterBillet": "Ajouter un type de billet",
    "total": "Total",
    "passerPaiement": "Passer au paiement",
    "recapitulatifCommande": "Récapitulatif de la commande",
    "billets": "Billets",
    "paiementTitre": "Paiement",
    "numCarte": "Numéro de carte",
    "numCartePlaceholder": "Numéro de carte",
    "dateExpiration": "Date d'expiration",
    "cvv": "CVV",
    "cvvPlaceholder": "CVV",
    "totalAPayer": "Total à payer",
    "payer": "Payer"
}