export default {
    monProfil: "Mon Profil",
    mesReservations: "Mes réservations",
    mesNotifications: "Mes notifications",
    donneesPersonnelles: "Données personnelles",
    modifier: "Modifier",
    sauvegarder: "Sauvegarder les modifications",
    madameMonsieur: "M./Mme",
    telephone: "Numéro de téléphone",
    email: "Email",
    adresse: "Adresse",
    motDePasse: "Mot de passe",
    changerMdp: "Changer de mot de passe",
    accepter: "Accepter",
    motDePasseActuel: "Mot de passe actuel",
    motDePassePlaceholder: "Votre mot de passe",
    nouveauMotDePasse: "Nouveau mot de passe",
    nouveauMotDePassePlaceholder: "Votre nouveau mot de passe",
    verificationMdp: "Vérification mot de passe",
    verificationMdpPlaceholder: "Confirmez votre mot de passe",
    reservationLe: "Réservation le",
    a: "à",
    annuler: "Annuler",
    aucuneNotifications: "Aucune notification",
    nomPrenomPlaceholder: "Nom et prénom",
    telephonePlaceholder: "Numéro de téléphone",
    emailPlaceholder: "Email",
    adressePlaceholder: "Adresse",
}
