export default {

    title: "Formulaire Prestataire",
    nom: "Nom :",
    nom_en : "Nom (EN) :",
    description: "Description :",
    description_en: "Description (EN) :",
    descriptionAccueil: "Description Accueil :",
    descriptionAccueil_en: "Description Accueil (EN) :",
    categorie: "Catégorie :",
    idEmplacement: "ID Emplacement :",
    image: "Image :",
    previewImageAlt: "Prévisualisation de l'image",
    servicesSectionTitle: "Services :",
    nomService: "Nom du Service :",
    descriptionService: "Description du Service :",
    lienService: "Lien du Service :",
    statutService: "Statut du Service :",
    statutActif: "Actif",
    statutInactif: "Inactif",
    supprimerService: "Supprimer le Service",
    ajouterService: "Ajouter un Service",
    soumettre: "Soumettre",
    dons : "Dons :",
}